//===================================================================//
//   Beat Tracking Alogrithm                                         //
//   Implemented on Software for Microsoft® Windows®                 //
//                                                                   //
//   Team of Sharif University of Technology - IRAN                  //
//                                                                   //
//   IEEE Signal Processing Cup 2017 - Beat Tracking Challenge       //
//                                                                   //
//   Please read the associated documentation on the procedure of    //
//   building the source code into executable app package and also   //
//   the installation.                                               //
//===================================================================//
//Notice: This file is autogenerated from a Simulink model
//  Parts marked with !@! are altered to meet requirements of the
//  GUI app.

/*
 * File: Beat_Tracking_Stem_types.h
 *
 * Code generated for Simulink model 'Beat_Tracking_Stem'.
 *
 * Model version                  : 1.83
 * Simulink Coder version         : 8.10 (R2016a) 10-Feb-2016
 * C/C++ source code generated on : Mon Jan 02 19:30:47 2017
 *
 * Target selection: ert.tlc
 * Embedded hardware selection: Intel->x86-64 (Windows64)
 * Code generation objectives: Unspecified
 * Validation result: Not run
 */

#ifndef RTW_HEADER_Beat_Tracking_Stem_types_h_
#define RTW_HEADER_Beat_Tracking_Stem_types_h_
#include "rtwtypes.h"
#include "builtin_typeid_types.h"
#include "multiword_types.h"

/* Custom Type definition for MATLAB Function: '<Root>/Overall Beat Period Estimation' */
#ifndef typedef_struct_T_Beat_Tracking_Stem_T
#define typedef_struct_T_Beat_Tracking_Stem_T

typedef struct {
  char_T f0[6];
  char_T f1[6];
} struct_T_Beat_Tracking_Stem_T;

#endif                                 /*typedef_struct_T_Beat_Tracking_Stem_T*/

#ifndef typedef_b_struct_T_Beat_Tracking_Stem_T
#define typedef_b_struct_T_Beat_Tracking_Stem_T

typedef struct {
  char_T f0[4];
} b_struct_T_Beat_Tracking_Stem_T;

#endif                                 /*typedef_b_struct_T_Beat_Tracking_Stem_T*/

/* Forward declaration for rtModel */
typedef struct tag_RTM_Beat_Tracking_Stem_T RT_MODEL_Beat_Tracking_Stem_T;

#endif                                 /* RTW_HEADER_Beat_Tracking_Stem_types_h_ */

/*
 * File trailer for generated code.
 *
 * [EOF]
 */
